<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
from scipy.linalg import solve

In [22]:
fruits_sold = np.array([[20,10],  #number of apples and oranges sold per day / coefficients of the linear equations
                        [17,22]])

total_price = np.array([[350],    #total revenue per day / constants of the linear equations
                        [500]])

price_of_apple_orange = np.linalg.inv(fruits_sold) @ total_price   #get price of apple and orange / values of the unknown variables by getting the dot product of the inverse the matrix fruits sold and matrix total price

print(price_of_apple_orange)

[[10.]
 [15.]]


In [23]:
#checking
checking = fruits_sold @ price_of_apple_orange #dot product of fruits sold and the prices for an apple and an orange to check if it's equal to the constants of the given linear equations
print(checking)

if 20*10 + 10*15 == 350:
  print('True')
else:
  print('False')

[[350.]
 [500.]]
True


In [24]:
coefficients = np.array([[4,3,2],     #matrix of the coefficients of the linear equations
                         [-2,2,3],
                         [3,-5,2]])

constants = np.array([[25],           #matrix of the constants of the linear equations
                      [-10],
                      [-4]])

unknown_variables = solve(np.linalg.inv(coefficients), constants) #use solve to solve for the values of the unknown variables from the inverse of the matrix coefficients and the matrix constants

print(unknown_variables) #print the values of the unknown variables

[[ 62.]
 [-82.]
 [117.]]


In [25]:
verify = solve(coefficients, unknown_variables) #verify the values of the unknown variables by using solve to solve the matrix coefficients and unknown variables values to check if it's equal to the constants of the given linear equations 
print(verify)

[[ 25.]
 [-10.]
 [ -4.]]
