<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np # import numpy

In [20]:
print('Matrix A: ')
A = np.array([[1,2,-1],
              [4,6,-2],
              [-1,3,3]])

print(A)
print()
print(f'Raw Determinant = {np.linalg.det(A)}') # get the determinant - raw value
print(f'Rounded Determinant = {round(np.linalg.det(A))}') # round to the nearest integer

Matrix A: 
[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]

Raw Determinant = -13.999999999999996
Rounded Determinant = -14
