<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Eigenvector_and_Eigenvalues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np
from numpy.linalg import eig
#from scipy.linalg import solve

In [50]:
A = np.array([[-12, 3], # create matrix A
              [4, 1]])

print(f'Matrix A:\n {A}')                # print matrix A

inv_A = np.linalg.inv(A)  # get the inverse of matrix A

print(f'\nInverse of Matrix A:\n{inv_A}')       # print the inverse of matrix A

B = np.array([[0],        # create matrix B
              [0]])

print(f'\nMatrix B:\n {B}')           # print matrix B

X = np.dot(inv_A, B)      # get the dot product of the inverse of matrix A and matrix B

print(f'\nDot product:\n{X}')           # print the solved dot product - wrong

Matrix A:
 [[-12   3]
 [  4   1]]

Inverse of Matrix A:
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]

Matrix B:
 [[0]
 [0]]

Dot product:
[[0.]
 [0.]]


#Example 1

In [51]:
A = np.array([[-6, 3],  # create matrix A
              [4, 5]])

print(f'Matrix A:\n{A}')

value, vector = np.linalg.eig(A) # use the eig method in order to get the eigenvalue and eigenvector of a square matrix A

print(f'\nThe Eigenvalue/s is/are: {value}')  # print the eigenvalues

print(f'\nThe right Eigenvectors are: \n{vector}')  # print the eigenvectors

#print(f'\nThe right Eigenvectors are: \n{vector.round()}') # print the rounded eigenvectors

Matrix A:
[[-6  3]
 [ 4  5]]

The Eigenvalue/s is/are: [-7.  6.]

The right Eigenvectors are: 
[[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


#Example 2

In [52]:
A = np.array([[2, 2, 4],  # create matrix A
              [1, 3, 5],
              [2, 3, 4]])

print(A)  # print matrix A

value, vector = np.linalg.eig(A)  # use the eig method in order to get the eigenvalue and eigenvector of a square matrix A

print(f'\nThe Eigenvalue/s is/are: {value.round()}')  # print the eigenvalues

print(f'\nThe right Eigenvectors are: \n{vector.round()}\n')  # print the eigenvectors

C = np.dot(A, vector.round()) # get the dot product of matrix A and the eigenvector

print(f'Dot product:\n {C}') # print the dot product

[[2 2 4]
 [1 3 5]
 [2 3 4]]

The Eigenvalue/s is/are: [ 9.  1. -1.]

The right Eigenvectors are: 
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]

Dot product:
 [[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
