<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
from scipy.linalg import solve
from numpy.linalg import eig

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [33]:
students = np.array([[1,1,1],
                     [1,0,4],
                     [0,0,5]])
total = np.array([[89],
                  [89],
                  [89]])

per_student = np.linalg.inv(students) @ total

print(per_student)


[[17.8]
 [53.4]
 [17.8]]


Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

In [30]:
coefficients = np.array([[3, -1, 1],
                         [9, -3, 3],
                         [-12, 4, -4]])

constants = np.array([[5],
                      [15],
                      [-20]])

unknown_values = np.linalg.pinv(coefficients) @ constants # since there was an error, i tried to use pseudo inverse in getting the inverse of the coefficients matrix

print(unknown_values)

[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


In [31]:
coefficients = np.array([[3, -1, 1],
                         [9, -3, 3],
                         [-12, 4, -4]])

constants = np.array([[5],
                      [15],
                      [-20]])

unknown_values = np.linalg.inv(coefficients) @ constants

print(unknown_values)

LinAlgError: ignored

For problem number 2, there was an error called singular matrix which means that the inverted matrix, coefficents matrix, cannot be inverted. This also means that the determinant is zero since it has no solution. Hence, the matrix should be a non singular matrix for it to not have a non zero determinant.


Problem 3. Consider the matrix, (40 points)

In [32]:
A = np.array([[8, 5, -6],
              [-12, -9, 12],
              [-3, -3, 5]])

value, vector = np.linalg.eig(A) # use the eig method in order to get the eigenvalue and eigenvector of a square matrix A

print(f'\nThe Eigenvalue/s is/are: {value}')  # print the eigenvalues

print(f'\nThe right Eigenvectors are: \n{vector}')  # print the eigenvectors

print(f'\nThe right Eigenvectors are: \n{vector.round()}') # print the rounded eigenvectors


The Eigenvalue/s is/are: [-1.  3.  2.]

The right Eigenvectors are: 
[[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]

The right Eigenvectors are: 
[[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
