<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Linear_Transformation_Demo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Using Python Codes, to find the inverse of a matrix, the matrix is passed to the linalg.inv() method of the Numpy module 

In [3]:
import numpy as np

In [11]:
A = np.array([[4,3],      #creation of matrix A
              [-5,9]])
print(A)

inv_A = np.linalg.inv(A)  #get the inverse of A
print(inv_A)

[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [12]:
B = np.array([[20],
              [26]])
print(B)

[[20]
 [26]]


In [39]:
X = inv_A @ B #dot product of inv_A and B
print(X)

[[2.]
 [4.]]


In [40]:
X = np.dot(inv_A,B) #dot product of inv_A and B
print(X)

[[2.]
 [4.]]


In [41]:
C = np.array([[4,3,2],    #matrix C
              [-2,2,3],
              [3,-5,2]])

#inv_C = np.linalg.inv(C)   #get the inverse of C

D = np.array([[25],       #matrix D
              [-10],
              [-4]])

E = np.linalg.inv(C) @ D  #dot product of the inverse of C and D

print(E)


[[ 5.]
 [ 3.]
 [-2.]]


##Application


In [42]:
fruits_sold = np.array([[20,10], #number of apples and oranges sold per day
                        [17,22]])

total_price = np.array([[350],    #total revenue per day
                        [500]])

price_of_apple_orange = np.linalg.inv(fruits_sold) @ total_price   #get price of apple and orange 

print(price_of_apple_orange)

[[10.]
 [15.]]


In [44]:
#checking
checking = fruits_sold @ price_of_apple_orange #dot product of fruits sold and the prices for an apple and an orange
print(checking)

if 20*10 + 10*15 == 350:
  print('True')
else:
  print('False')

[[350.]
 [500.]]
True
