<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python program to inverse


In [1]:
import numpy as np

In [48]:
A = np.array([[1, 2],
              [4, 7]])

invA = np.linalg.inv(A) # inverse of matrix A

print(invA) # print the inverse of matrix A

[[-7.  2.]
 [ 4. -1.]]


In [49]:
C = np.dot(A, invA) # get identity matrix
print(C) # print dot product

[[1. 0.]
 [0. 1.]]


##Python Program to Inverse and Transpose a 3x3 Matrix




In [52]:
A = np.array([[6, 1, 1],
              [4,-2, 5],
              [2, 8, 7]])

InvOfA = np.linalg.inv(A) # to inverse matrix A

B = np.transpose(A) # to transpose matrix A

print(A)

print()

print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [33]:
dot = np.dot(A, InvOfA) # get dot product of A and its inverse

print(dot)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]


In [38]:
# practice
M = np.array([[1,7],
             [-3, 5]])

np.array(M @ np.linalg.inv(M), dtype=int) # get the dot product of M and the inverse of M then convert it to integers to get the identity matrix

array([[1, 0],
       [0, 1]])

In [41]:
# practice
A = np.array([[3, 2, 3],
              [4, 19, 6],
              [74, 2, 9]])

B = np.linalg.inv(A)

np.array(A @ B, dtype=int) # get the dot product of A and B then convert it to integers to get the identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

##Coding Activity 3 - Python Exercise 3
Create a Python Program to inverse and transpose a 4x4 matrix




In [53]:
A = np.array([[6,1,1,3],
              [4,-2,5,1],
              [2,8,7,6],
              [3,1,9,7] ])

InvA = np.linalg.inv(A) # to inverse matrix A
TransposeA = np.transpose(A) # to transpose matrix A

print('The inverse of Matrix A is: ')
print(InvA) # print inverse of matrix A

print()

print('The tranpose of Matrix A is: ')
print(TransposeA) # print transpose of matrix A

The inverse of Matrix A is: 
[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]

The tranpose of Matrix A is: 
[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
