<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Midterm Exam - Banta, Ian Noel M.


In [ ]:
import numpy as np # import numpy as np

Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [ ]:
square_matrix = np.identity(5) # create a 5x5 matrix using the method called identity/eye, with 5 as argument for the length of the square

print(f'Square Matrix whose length is 5: \n{square_matrix}') # print the square matrix with a length of 5: 5 rows and 5 columns

Square Matrix whose length is 5: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [ ]:
upper_triangular_matrix = np.array([[1,2,3],
                                    [0,3,1],
                                    [0,0,5]]) # create a square matrix with the length of 3 or 3x3 with the lower triangle being all zeros

print(f'Upper triangular matrix: \n{upper_triangular_matrix}') # print the square upper triangular matrix with 0s below the principal diagonal

Upper triangular matrix: 
[[1 2 3]
 [0 3 1]
 [0 0 5]]


Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [ ]:
symmetrical_square_matrix = np.array([[1,1,1],
                                      [1,2,2],
                                      [1,2,3]]) # create a symmetrical square matrix

transpose = np.transpose(symmetrical_square_matrix) # transpose the symmetrical square matrix 

print(f'Symmetrical square matrix: \n{symmetrical_square_matrix}') # print the symmetrical square matrix

print('\nTo prove that it is syemmetrical: \n')

print(f'Transposed matrix: \n{transpose}') # print the transposed matrix

Symmetrical square matrix: 
[[1 1 1]
 [1 2 2]
 [1 2 3]]

To prove that it is syemmetrical: 

Transposed matrix: 
[[1 1 1]
 [1 2 2]
 [1 2 3]]


Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [ ]:
C = np.array([[1,2,3],
              [2,3,3],
              [3,4,-2]]) # create matrix C

inverse_of_matrix_C = np.linalg.inv(C) # use linalg.inv method to get the inverse of matrix C

print(f'The inverse of Matrix C: \n{inverse_of_matrix_C}') # print the inverse of matrix C

The inverse of Matrix C: 
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [26]:
determinant_of_matrix_C = np.linalg.det(C) # use the linalg.der method with matrix C as the argument in order to get the determinant of matrix C

print(f'Raw Determinant of Matrix C: {determinant_of_matrix_C}') # print raw determinant of matrix C

print(f'Rounded Determinant of Matrix C: {round(determinant_of_matrix_C)}') # print rounded determinant of matrix C

Raw Determinant of Matrix C: 5.000000000000001
Rounded Determinant of Matrix C: 5


Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [ ]:
Equations = np.array([[5,4,1],
                      [10,9,4],
                      [10,13,15]]) # create a matrix based on the coefficients of the equations

Constants = np.array([[[3.4],
                       [8.8],
                       [19.2]]]) # create a matrix based on the constants of the equations

roots = np.linalg.inv(Equations) @ Constants # use @ in order to get the dot product of the inverse of the equations matrix and the constants matrix

print(f'The roots are: \n{roots}') # print the roots from the dot product

The roots are: 
[[[0.2]
  [0.4]
  [0.8]]]
