<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Practical Lab Exam 1


In [47]:
import numpy as np

In [48]:
## Problem 1. Consider the four matrices,
print('Problem 1.\n')

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])

C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

D = np.array([[1, 2],
              [3, 4]])

## a.) AB

print('a.\n')
dot = np.dot(A,B)
print(dot)


## b.) D + D

sum = np.add(D,D)
print('\nb.\n')
print(sum)


## c.) 2C 

product = 2 * C
print('\nc.\n')
print(product)




Problem 1.

a.

[[22 28]
 [49 64]]

b.

[[2 4]
 [6 8]]

c.

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [49]:
print('Problem 2.\n')
theta = np.array([5, 3, -1])

print(f'Matrix: {theta}')

#type

print(f'Type: {type(theta)}')

#shape

print(f'Shape: {theta.shape}')

#dimension

print(f'Dimension: {theta.ndim}')

#size

print(f'Size: {theta.size}')

Problem 2.

Matrix: [ 5  3 -1]
Type: <class 'numpy.ndarray'>
Shape: (3,)
Dimension: 1
Size: 3
