<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
##import numpy and call it np 
import numpy as np

Question 1. (20 points) Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C". 

In [23]:
## identity matrix using identity method, diagonal elements are all 1 
## can also use np.eye(4) or np.diag to a matrix that has 1s in it \
## np.identity creates a matrix that takes in a number n as the number of rows and columns and sets the diagonal to 1s.
C = np.identity(4) 
print("Answer: \n")
print(C) ## print matrix C

Answer: 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 2. (20 points) In relation to Question 1, show a solution that doubles all the values of each element. 

In [24]:
## double all the values in matrix C by multiplying it to 2 
D = C * 2
print("Answer: \n")
print(D)

Answer: 

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Question 3. (10 points) Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8]. 

In [25]:
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

## use np.cross to get the cross product for matrix A and B
cross = np.cross(A,B)
print("Answer: \n")
print(cross)

Answer: 

[20 -4 -3]
