<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Algebra and its operations

In [3]:
import numpy as np

A = np.array([[-5, 0],
              [4, 1]])
B = np.array([[6, -3],
              [2, 3]])

Addition

In [4]:
sum = A +B 
print(sum)

[[ 1 -3]
 [ 6  4]]


Subtraction

In [6]:
difference1 = B - A
difference2 = A - B

print(difference1)
print(' ')
print(difference2)

[[11 -3]
 [-2  2]]
 
[[-11   3]
 [  2  -2]]
