<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Representing Vectors

In [36]:
import numpy as np

A = np.array([4, 3])
B = np.array([2, -5])

print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


##Describing Vectors in Numpy

In [37]:
###Checking shapes
###Shapes tells us how many rows and columns are there

ball1 = np.array([1, 2, 3])
ball2 = np.array([0, 1, -1])
pool = np.array([ball1, ball2]) ##Matrix

pool.shape #number of rows and columns
pool.ndim  #checking dimensions

2

In [38]:
U = np.array([[1, 2, 3], 
              [4, 5, 6]])

U
U.shape  #number of rows and columns
U.size   #number of elements in a vector

6

##Space

Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations

Addition of Vectors

In [39]:
addend1 = np.array([0, 0, 0])
addend2 = np.array([1, 1, 0])
sum = addend1 + addend2
print(sum)

[1 1 0]


In [40]:
resultant = np.add(addend1, addend2)
print(resultant)

[1 1 0]


Subtraction of Vectors

In [41]:
difference = np.subtract(addend1, addend2)
difference

array([-1, -1,  0])

Multiplication of Vectors

In [42]:
A = np.array([1, 5, 8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

Cross Product

In [43]:
A = np.array([2, 3])
B = np.array([1, 7])

output = np.cross(A,B)

output

array(11)

In [44]:
C = np.array([2, 3, 4])
D = np.array([1, 7, 1])
cross = np.cross(C,D)
cross

array([-25,   2,  11])

Dot Product

In [45]:
dot = np.dot(A,B)
dot

23