<a href="https://colab.research.google.com/github/Yaniii2021/Linear-Algebra-58019/blob/main/Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Algebra 

In [1]:
import numpy as np 

In [4]:
a = np.array([1,2,3]) #This is an example of a 1x3 matrix
print(a)

[1 2 3]


In [7]:
b = np.array([[1,2,3],
             [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
c = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
d = np.full((3,3), 7)
print(d)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [13]:
e = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(e)

e = np.diagonal([
              [1,2,3],
              [4,5,6],
              [7,8,9]])
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [15]:
f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
g = np.zeros((3,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
h = np.empty((0,12))
print(h)

[]


#Operations

In [21]:
print(d+d)

[[14 14 14]
 [14 14 14]
 [14 14 14]]


In [22]:
print(d-d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
